src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>WTRC_Master__c</fullName>
        <description>WTRC Master</description>
        <label>WTRC Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WTRC_Username__c</fullName>
        <description>WTRC Username</description>
        <label>WTRC Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/WTRC_Shipment__c.object
<CustomObject>
    <fields>
        <fullName>Client_City__c</fullName>
        <description>Client City</description>
        <label>Client City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Country__c</fullName>
        <description>Client Country</description>
        <label>Client Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Email__c</fullName>
        <description>Client Email</description>
        <label>Client Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Client_Phone__c</fullName>
        <description>Client Phone</description>
        <label>Client Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Client_Street__c</fullName>
        <description>Client Street</description>
        <label>Client Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Zip__c</fullName>
        <description>Client Zip</description>
        <label>Client Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Parcel_Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master__c</fullName>
        <label>Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery on specified date/time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>Username</description>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WTRACE_XML__c</fullName>
        <label>Generated XML</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>WT Shipment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WT Shipment</pluralLabel>
    <recordTypes>
        <fullName>Shipment</fullName>
        <active>true</active>
        <description>Basic Shipment</description>
        <label>Shipment</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/WTRC_Shipment.cls
/**
 * Creation Date: 	20110118
 * Description: 	WTRC_Shipment
 * 
 * Author: 	ABSI - Bob Ceuppens
 */	
 
public with sharing class WTRC_Shipment {

	private WTRC_Shipment__c myShipment {get;set;}
	
	public WTRC_Shipment(WTRC_Shipment__c myShipment) {
        this.myShipment = myShipment;
    }
    
	public WTRC_Shipment() {
    }
        
	public void processShipment(List<WTRC_Shipment__c> shipmentsToProcess){
		
		List<Id> accountsFromShipment = new List<Id>();
		
		for(WTRC_Shipment__c myShipment : shipmentsToProcess){
			accountsFromShipment.add(myShipment.Client__c);
		}
		
		Map<Id,Account> accountsForReference = new Map<Id,Account>([select Id,ShippingCity,ShippingPostalCode,ShippingStreet,Email__c,Phone,ShippingCountry from Account where Id =:accountsFromShipment]);
		
		User currentUser = [select Id,WTRC_Username__c,WTRC_Master__c from User where Id =: System.Userinfo.getUserId()];
		
		for(WTRC_Shipment__c myShipment : shipmentsToProcess){
			if (true) {
				System.debug('ABSILOG *** myShipment.Id ' + myShipment.Id + ' myShipment.Client__r.ShippingCity ' + myShipment.Client__r.ShippingCity + ' ################') ;
				myShipment.Client_City__c = accountsForReference.get(myShipment.Client__c).ShippingCity;
				myShipment.Client_Zip__c = accountsForReference.get(myShipment.Client__c).ShippingPostalCode;
				myShipment.Client_Street__c = accountsForReference.get(myShipment.Client__c).ShippingStreet;
				myShipment.Client_Email__c = accountsForReference.get(myShipment.Client__c).Email__c;
				myShipment.Client_Phone__c = accountsForReference.get(myShipment.Client__c).Phone;
				myShipment.Client_Country__c = accountsForReference.get(myShipment.Client__c).ShippingCountry;
			}
			myShipment.Username__c = currentUser.WTRC_Username__c;
			myShipment.Master__c = currentUser.WTRC_Master__c;
			myShipment.Service__c = 'SHIPMENT';
		}
	}
	
	public void prepareShipmentForSubmit(){
		System.debug('################# ABSILOG - prepareShipmentForSubmit() ' + '##########');
    	Set <String> fieldsToExclude = new Set<String>();
    	fieldsToExclude.add('wtrace_xml__c');
		String myXML = WTRC_XMLBuilder.getWTRCXML(myShipment,fieldsToExclude);
		myShipment.WTRACE_XML__c = myXML;
		update myShipment;
	}
	
   public Id ship(){
   		System.debug('################# ABSILOG - ship() ' + '##########');
        WTRACE_LabelPrinting.WS_LabelPrintingPort myWS_stub = new WTRACE_LabelPrinting.WS_LabelPrintingPort();
        myWS_stub.timeout_x = 30000;
        try {
        	System.debug('################# ABSILOG - myShipment.Id ' + myShipment.Id + ' myShipment.WTRACE_XML__c ' + myShipment.WTRACE_XML__c + '##########');
			String[] myResponse;
			myResponse = myWS_stub.getLabelPDF(myShipment.WTRACE_XML__c,'rutenber');
            Attachment a = new Attachment();
            a.ParentId = myShipment.Id;
            a.Name = myResponse[0];
            a.Body = EncodingUtil.base64Decode(myResponse[1]);
            insert a;
            
            if (myResponse == null) {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Er zijn geen gegevens beschikbaar voor deze klant');
                ApexPages.addMessage(myMsg);
                return null;
            }
            System.debug('################# ABSILOG - myResponse ' + myResponse + '##########');
            return a.Id;
        }
        catch (CalloutException ex) {
        	 System.debug('################# ABSILOG - CalloutException ' + ex + '##########');
            ApexPages.Message myMsg;
            if (ex.getMessage().contains('IO Exception')) { 
                myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Er is een probleem opgetreden met het ophalen van de gegevens');
                ApexPages.addMessage(myMsg);
            }
            if (ex.getMessage().contains('parse')) {
                myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Er is een probleem opgetreden met het ophalen van de gegevens');
                ApexPages.addMessage(myMsg);
            }
            return null;
        }catch (Exception ex) {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Er is een ongekend probleem opgetreden. Gelieve de beheerder te contacteren');
            ApexPages.addMessage(myMsg);
            System.debug('################# ABSILOG - WTRACE_controllerLabelPrinter ' + ex.getMessage() + '##########');
            return null;
        }
    }

}